name: SonarCloud analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read  # allows SonarCloud to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Ensure this secret is set in GitHub repository secrets
        with:
          args:
            -Dsonar.projectKey=J4CIVY_LandingPage
            -Dsonar.organization=j4civy
            #-Dsonar.sources= # Uncomment and specify if source files are in a subdirectory
            #-Dsonar.tests= # Uncomment and specify if test files are in a subdirectory
          projectBaseDir: .  # Set to the correct directory if not the root
